---
title: "01-introduction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Digestive system cancer, also known as gastrointestinal cancer, is one of the most prevalent forms of cancer in the US today. However, the number of gastrointestinal cancers has been decreasing over the years. Some researchers believe that population wide changes in diet, such as more fruit and vegetables being consumed, contributed to this decrease in digestive system cancer incidence. Nutritional content of diet and calorie consumption has been shown to be related to the onset of digestive system cancer, but 

a) Does a population-level increase in consumption (calories) relate to population-level increases in digestive cancer incidence?

b) What about the nutritional content of food being eaten? Does a greater proportion of sugar or meat coincide with higher cancer incidence?

c) Is there a relationship between cancer incidence and cancer mortality? For instance, with higher incidence does treatment get better? Or, does incidence lead to a load on oncology units, decreasing quality of care?

