# Interactive

<!-- load d3 v6 -->
<script src="https://d3js.org/d3.v6.min.js"></script>

<!-- select food, incidence, mortality and update plot -->
<table><tr>
  <th><select name="selectFood" id="selectFood">
    <option value="peanuts">Peanuts</option>
    <option value="beef">Beef</option>
  </select></th>
  <th><select name="selectCancer" id="selectCancer">
    <option value="incidence">Incidence</option>
    <option value="mortality">Mortality</option>
  </select></th>
  <th><select name="selectSex" id="selectSex">
    <option value="male">Male</option>
    <option value="female">Female</option>
  </select></th>
  <th><button type="button" id="update">Update</button></th>
</tr></table>

<!-- div container for plot -->
<div id="plot"></div>

<!-- initialize data and plot elements -->
<script>
  var t = 1500;
  var base_url = "https://raw.githubusercontent.com/cpaynerogers/food-digestive-cancer";
  var data_path = "/master/resources/processed_data/";

  // row converters
  var foodConverter = function(d) {
    if (parseInt(d["Year"]) > 1999) {
      return {
        year: parseFloat(d["Year"]),
        wholeMilk: parseFloat(d["Whole Milk"]),
        twoPercentMilk: parseFloat(d["2% Milk"]),
        onePercentMilk: parseFloat(d["1% Milk"]),
        skimMilk: parseFloat(d["Skim Milk"]),
        wholeFlavoredMilk: parseFloat(d["Whole Flavored Milk"]),
        lowFatFlavored: parseFloat(d["Low Fat Flavored"]),
        butermilk: parseFloat(d["Buttermilk"]),
        yogurt: parseFloat(d["Yogurt"]),
        americanCheese: parseFloat(d["American Cheese"]),
        otherAmericanCheese: parseFloat(d["Other American Cheese"]),
        provolone: parseFloat(d["Provolone"]),
        romano: parseFloat(d["Romano"]),
        parmesan: parseFloat(d["Parmesan"]),
        mozzarella: parseFloat(d["Mozzarella"]),
        ricotta: parseFloat(d["Ricotta"]),
        otherItalianCheese: parseFloat(d["Other Italian Cheese"]),
        swiss: parseFloat(d["Swiss"]),
        brick: parseFloat(d["Brick"]),
        muenster: parseFloat(d["Muenster"]),
        blueCheese: parseFloat(d["Blue Cheese"]),
        otherMiscCheese: parseFloat(d["Other Misc Cheese"]),
        cottageCheese: parseFloat(d["Cottage Cheese"]),
        lowfatCottageCheese: parseFloat(d["Lowfat Cottage Cheese"]),
        iceCream: parseFloat(d["Ice Cream"]),
        losfatIceCream: parseFloat(d["Lowfat Ice Cream"]),
        otherFrozenDairy: parseFloat(d["Other Frozen Dairy"]),
        cannedMilk: parseFloat(d["Canned Milk"]),
        bulkCannedMilk: parseFloat(d["Bulk Canned Milk"]),
        skimCannedMilk: parseFloat(d["Skim Canned Milk"]),
        wholeDryMilk: parseFloat(d["Whole Dry Milk"]),
        nonfatDryMilk: parseFloat(d["Nonfat Dry Milk"]),
        dryButtermilk: parseFloat(d["Dry Buttermilk"]),
        halfAndHalf: parseFloat(d["Half and Half"]),
        eggnog: parseFloat(d["Eggnog"]),
        creamProducts: parseFloat(d["Cream Products"]),
        butter: parseFloat(d["Butter"]),
        margarine: parseFloat(d["Margarine"]),
        lard: parseFloat(d["Lard"]),
        beefTallow: parseFloat(d["Beef Tallow"]),
        shortening: parseFloat(d["Shortening"]),
        saladCookingOils: parseFloat(d["Salad, Cooking Oils"]),
        otherAddedFats: parseFloat(d["Other Added Fats"]),
        lightCream: parseFloat(d["Light Cream"]),
        halfAndHalf: parseFloat(d["Half and Half"]),
        heavyCream: parseFloat(d["Heavy Cream"]),
        sourCream: parseFloat(d["Sour Cream"]),
        creamCheese: parseFloat(d["Cream Cheese"]),
        eggnog: parseFloat(d["Eggnog"]),
        oranges: parseFloat(d["Oranges"]),
        tangerines: parseFloat(d["Tangerines"]),
        grapefruit: parseFloat(d["Grapefruit"]),
        lemons: parseFloat(d["Lemons"]),
        limes: parseFloat(d["Limes"]),
        apples: parseFloat(d["Apples"]),
        apricots: parseFloat(d["Apricots"]),
        avocados: parseFloat(d["Avocados"]),
        bananas: parseFloat(d["Bananas"]),
        blueberries: parseFloat(d["Blueberries"]),
        cantaloupe: parseFloat(d["Cantaloupe"]),
        cherries: parseFloat(d["Cherries"]),
        cranberries: parseFloat(d["Cranberries"]),
        grapes: parseFloat(d["Grapes"]),
        honeydewMelons: parseFloat(d["Honeydew Melons"]),
        kiwi: parseFloat(d["Kiwi"]),
        mangoes: parseFloat(d["Mangoes"]),
        peaches: parseFloat(d["Peaches"]),
        pears: parseFloat(d["Pears"]),
        pineapple: parseFloat(d["Pineapple"]),
        papayas: parseFloat(d["Papayas"]),
        plums: parseFloat(d["Plums"]),
        raspberries: parseFloat(d["Raspberries"]),
        strawberries: parseFloat(d["Strawberries"]),
        watermelon: parseFloat(d["Watermelon"]),
        cannedApples: parseFloat(d["Canned Apples"]),
        cannedApricots: parseFloat(d["Canned Apricots"]),
        cannedCherries: parseFloat(d["Canned Cherries"]),
        cannedOlives: parseFloat(d["Canned Olives"]),
        cannedPeaches: parseFloat(d["Canned Peaches"]),
        cannedPears: parseFloat(d["Canned Pears"]),
        cannedPineapple: parseFloat(d["Canned Pineapple"]),
        cannedPlum: parseFloat(d["Canned Plum"]),
        frozenBlackberries: parseFloat(d["Frozen Blackberries"]),
        frozenBlueberries: parseFloat(d["Frozen Blueberries"]),
        frozenRaspberries: parseFloat(d["Frozen Raspberries"]),
        frozenStrawberries: parseFloat(d["Frozen Strawberries"]),
        otherFrozenBerries: parseFloat(d["Other Frozen Berries"]),
        frozenApples: parseFloat(d["Frozen Apples"]),
        frozenApricots: parseFloat(d["Frozen Apricots"]),
        frozenCherries: parseFloat(d["Frozen Cherries"]),
        frozenPeaches: parseFloat(d["Frozen Peaches"]),
        frozenPlumsAndPrunes: parseFloat(d["Frozen Plums and Prunes"]),
        otherFrozenFruits: parseFloat(d["Other Frozen Fruits"]),
        driedApples: parseFloat(d["Dried Apples"]),
        driedApricots: parseFloat(d["Dried Apricots"]),
        driedDates: parseFloat(d["Dried Dates"]),
        driedFigs: parseFloat(d["Dried Figs"]),
        driedPeaches: parseFloat(d["Dried Peaches"]),
        driedPears: parseFloat(d["Dried Pears"]),
        driedPlums: parseFloat(d["Dried Plums"]),
        driedRaisins: parseFloat(d["Dried Raisins"]),
        orangeJuice: parseFloat(d["Orange Juice"]),
        grapefruitJuice: parseFloat(d["Grapefruit Juice"]),
        lemonJuice: parseFloat(d["Lemon Juice"]),
        limeJuice: parseFloat(d["Lime Juice"]),
        appleJuice: parseFloat(d["Apple Juice"]),
        cranberryJuice: parseFloat(d["Cranberry Juice"]),
        grapeJuice: parseFloat(d["Grape Juice"]),
        pineappleJuice: parseFloat(d["Pineapple Juice"]),
        pruneJuice: parseFloat(d["Prune Juice"]),
        whiteWholeFlour: parseFloat(d["White, Whole Flour"]),
        durumFlour: parseFloat(d["Durum Flour"]),
        ryeFlour: parseFloat(d["Rye Flour"]),
        rice: parseFloat(d["Rice"]),
        cornFlourMeal: parseFloat(d["Corn Flour, Meal"]),
        hominyAndGrits: parseFloat(d["Hominy and Grits"]),
        cornstarch: parseFloat(d["Cornstarch"]),
        oatProducts: parseFloat(d["Oat Products"]),
        barleyProducts: parseFloat(d["Barley Products"]),
        beef: parseFloat(d["Beef"]),
        veal: parseFloat(d["Veal"]),
        pork: parseFloat(d["Pork"]),
        lamb: parseFloat(d["Lamb"]),
        chicken: parseFloat(d["Chicken"]),
        turkey: parseFloat(d["Turkey"]),
        freshFish: parseFloat(d["Fresh Fish"]),
        freshShellfish: parseFloat(d["Fresh Shellfish"]),
        cannedSalmon: parseFloat(d["Canned Salmon"]),
        cannedSardines: parseFloat(d["Canned Sardines"]),
        cannedTuna: parseFloat(d["Canned Tuna"]),
        cannedShellfish: parseFloat(d["Canned Shellfish"]),
        otherCanned: parseFloat(d["Other Canned"]),
        eggs: parseFloat(d["Eggs"]),
        peanuts: parseFloat(d["Peanuts"]),
        almonds: parseFloat(d["Almonds"]),
        hazelnuts: parseFloat(d["Hazelnuts"]),
        pecans: parseFloat(d["Pecans"]),
        walnuts: parseFloat(d["Walnuts"]),
        macadamiaNuts: parseFloat(d["Macadamia nuts"]),
        pistachios: parseFloat(d["Pistachios"]),
        otherNuts: parseFloat(d["Other nuts"]),
        coconuts: parseFloat(d["Coconuts"]),
        caneBeetSugar: parseFloat(d["Cane, Beet Sugar"]),
        cornSyrup: parseFloat(d["Corn Syrup"]),
        glucose: parseFloat(d["Glucose"]),
        dextrose: parseFloat(d["Dextrose"]),
        edibleSyrups: parseFloat(d["Edible Syrups"]),
        honey: parseFloat(d["Honey"]),
        artichokes: parseFloat(d["Artichokes"]),
        asparagus: parseFloat(d["Asparagus"]),
        bellPeppers: parseFloat(d["Bell Peppers"]),
        broccoli: parseFloat(d["Broccoli"]),
        brusselsSprouts: parseFloat(d["Brussels Sprouts"]),
        cabbage: parseFloat(d["Cabbage"]),
        carrots: parseFloat(d["Carrots"]),
        cauliflower: parseFloat(d["Cauliflower"]),
        celery: parseFloat(d["Celery"]),
        collardGreens: parseFloat(d["Collard Greens"]),
        sweetCorn: parseFloat(d["Sweet Corn"]),
        cucumbers: parseFloat(d["Cucumbers"]),
        eggplant: parseFloat(d["Eggplant"]),
        escarole: parseFloat(d["Escarole"]),
        garlic: parseFloat(d["Garlic"]),
        headLettuce: parseFloat(d["Head Lettuce"]),
        kale: parseFloat(d["Kale"]),
        romaineLettuce: parseFloat(d["Romaine Lettuce"]),
        limaBeans: parseFloat(d["Lima Beans"]),
        mushrooms: parseFloat(d["Mushrooms"]),
        mustardGreens: parseFloat(d["Mustard Greens"]),
        okra: parseFloat(d["Okra"]),
        onions: parseFloat(d["Onions"]),
        potatoes: parseFloat(d["Potatoes"]),
        pumpkin: parseFloat(d["Pumpkin"]),
        radishes: parseFloat(d["Radishes"]),
        snapBeans: parseFloat(d["Snap Beans"]),
        spinach: parseFloat(d["Spinach"]),
        squash: parseFloat(d["Squash"]),
        sweetPotatoes: parseFloat(d["Sweet Potatoes"]),
        tomatoes: parseFloat(d["Tomatoes"]),
        turnipGreens: parseFloat(d["Turnip Greens"]),
        cannedAsparagus: parseFloat(d["Canned Asparagus"]),
        cannedSnapBeans: parseFloat(d["Canned Snap Beans"]),
        cannedCabbage: parseFloat(d["Canned Cabbage"]),
        cannedCarrots: parseFloat(d["Canned Carrots"]),
        cannedSweetCorn: parseFloat(d["Canned Sweet Corn"]),
        cannedCucumbers: parseFloat(d["Canned Cucumbers"]),
        cannedGreenPeas: parseFloat(d["Canned Green Peas"]),
        cannedMushrooms: parseFloat(d["Canned Mushrooms"]),
        cannedChilePeppers: parseFloat(d["Canned Chile Peppers"]),
        cannedPotatoes: parseFloat(d["Canned Potatoes"]),
        cannedTomatoes: parseFloat(d["Canned Tomatoes"]),
        otherCannedVegetables: parseFloat(d["Other Canned Vegetables"]),
        frozenAsparagus: parseFloat(d["Frozen Asparagus"]),
        frozenSnapBeans: parseFloat(d["Frozen Snap Beans"]),
        frozenBroccoli: parseFloat(d["Frozen Broccoli"]),
        frozenCarrots: parseFloat(d["Frozen Carrots"]),
        frozenCauliflower: parseFloat(d["Frozen Cauliflower"]),
        frozenSweetCorn: parseFloat(d["Frozen Sweet Corn"]),
        frozenGreenPeas: parseFloat(d["Frozen Green Peas"]),
        frozenLimaBeans: parseFloat(d["Frozen Lima Beans"]),
        frozenPotatoes: parseFloat(d["Frozen Potatoes"]),
        frozenSpinach: parseFloat(d["Frozen Spinach"]),
        otherFrozenVegetables: parseFloat(d["Other Frozen Vegetables"]),
        dehydratedOnions: parseFloat(d["Dehydrated Onions"]),
        dehydratedPotatoes: parseFloat(d["Dehydrated Potatoes"]),
        chipsPotatoes: parseFloat(d["Chips, Potatoes"]),
        dryEdibleBeans: parseFloat(d["Dry Edible Beans"]),
        dryPeasAndLentils: parseFloat(d["Dry Peas and Lentils"])
      }
    }
  };
  var incidenceMaleConverter = function(d) {
    if (parseInt(d["Year"]) > 1999) {
      if (d["Sex"] === "Male") {
        return {
          year: parseFloat(d["Year"]),
          sex: d["Sex"],
          rate: parseFloat(d["Rate"]),
          cases: parseFloat(d["Cases"]),
          population: parseFloat(d["Population"])
        }
      }
    }
  };
  var incidenceFemaleConverter = function(d) {
    if (parseInt(d["Year"]) > 1999) {
      if (d["Sex"] === "Female") {
        return {
          year: parseFloat(d["Year"]),
          sex: d["Sex"],
          rate: parseFloat(d["Rate"]),
          cases: parseFloat(d["Cases"]),
          population: parseFloat(d["Population"])
        }
      }
    }
  };
  var mortalityMaleConverter = function(d) {
    if (parseInt(d["Year"]) > 1999) {
      if (d["Sex"] === "Male") {
        return {
          year: parseFloat(d["Year"]),
          sex: d["Sex"],
          rate: parseFloat(d["Rate"]),
          cases: parseFloat(d["Cases"]),
          population: parseFloat(d["Population"])
        }
      }
    }
  };
  var mortalityFemaleConverter = function(d) {
    if (parseInt(d["Year"]) > 1999) {
      if (d["Sex"] === "Female") {
        return {
          year: parseFloat(d["Year"]),
          sex: d["Sex"],
          rate: parseFloat(d["Rate"]),
          cases: parseFloat(d["Cases"]),
          population: parseFloat(d["Population"])
        }
      }
    }
  };

  // read in csv data
  var csvErrorFunction = function(e) {console.log(e)};
  var dataset = {
    mortality: {},
    incidence: {}
  };
  d3.csv(
      base_url + data_path + "food.csv",
      foodConverter)
    .then(function(data) {
      dataset.food = data
    })
    .catch(csvErrorFunction);
  d3.csv(
      base_url + data_path + "incidence.csv",
      incidenceMaleConverter)
    .then(function(data) {
      dataset.incidence.male = data
    })
    .catch(csvErrorFunction);
  d3.csv(
      base_url + data_path + "incidence.csv",
      incidenceFemaleConverter)
    .then(function(data) {
      dataset.incidence.female = data
    })
    .catch(csvErrorFunction);
  var mortalityMale = d3.csv(
      base_url + data_path + "mortality.csv",
      mortalityMaleConverter)
    .then(function(data) {
      dataset.mortality.male = data
    })
    .catch(csvErrorFunction);
  var mortalityFemale = d3.csv(
      base_url + data_path + "mortality.csv",
      mortalityFemaleConverter)
    .then(function(data) {
      dataset.mortality.female = data
    })
    .catch(csvErrorFunction);

  // margins and overall width/height
  var width = 770;
  var height = 640;
  var margin = {top: 25, right: 25, bottom: 25, left: 25};

  // create svg inside div
  var svg = d3.select("div#plot")
    .append("svg")
      .attr("width", width)
      .attr("height", height)
  svg.append("g")
      .attr("id", "xAxis")
      .attr("transform", "translate(0," + (height-margin.top-margin.bottom) + ")")
  svg.append("g")
      .attr("id", "yAxis")

  // update callback
  // data is redefined here and ... hopefully promises have been fulfilled?
  d3.select("#update").on("click", function () {
    // get food choice
    var foodSelection = document.getElementById('selectFood');
    var foodChoice = foodSelection.options[foodSelection.selectedIndex].value;

    // get cancer choice
    var cancerSelection = document.getElementById('selectCancer');
    var cancerChoice = cancerSelection.options[cancerSelection.selectedIndex].value;

    // get sex choice
    var sexSelection = document.getElementById('selectSex');
    var sexChoice = sexSelection.options[sexSelection.selectedIndex].value;

    // combine x- and y-data
    var x = dataset["food"];
    var y = dataset[cancerChoice][sexChoice];
    var xy = x.map(function(e, i) {
      return [e, y[i]]
    });

    // x-axis is linear food
    var xScale = d3.scaleLinear()
      .domain([
        d3.min(dataset["food"], function(d, i) {
          return d[foodChoice];
        }),
        d3.max(dataset["food"], function(d, i) {
          return d[foodChoice];
        })
      ])
      .range([margin.left, width-margin.right])
    d3.select("g#xAxis")
      .attr("transform", "translate(0," + (height-margin.top-margin.bottom) + ")")
      .transition()
      .duration(t)
      .call(d3.axisBottom(xScale));

    // y-axis is also linear
    var yScale = d3.scaleLinear()
      .domain([
        d3.min(
          dataset[cancerChoice][sexChoice],
          function(d, i) {
            return d["rate"];
          }
        ),
        d3.max(
          dataset[cancerChoice][sexChoice],
          function(d, i) {
            return d["rate"];
          }
        )
      ])
      .range([height-margin.bottom, margin.top])
    d3.select("g#yAxis")
      .attr("transform", "translate(" + margin.left + ", 0)")
      .transition()
      .duration(t)
      .call(d3.axisLeft(yScale));

    // add dots at pixel locations
    circles = svg.selectAll("circle")
    circles
      .data(xy)
      .enter()
      .append("circle")
      .merge(circles)
      .transition()
      .duration(t)
      .attr("cx", function(d, i) {
        return xScale(d[0][foodChoice]);
      })
      .attr("cy", function(d) {
        return yScale(d[1]["rate"]);
      })
      .attr("r", "3");
  })
</script>
