# Conclusion

We found interesting and satisfactory answers to our initial questions. We observed that digestive cancer incidence and mortality are both decreasing, with mortality increasing rapidly in the past couple of years. This may be due to the advances in [digestive system cancer treatment](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4974579/) such as more frequent colonoscopies, monitoring of gut bacteria levels, and novel chemotherapy treatments. All of these advancements have happened in the last couple of decades and have done well to reduce the number of deaths and cases for digestive system cancer.

We saw that overall caloric intake is associated with digestive cancer, both of which have been decreasing as a whole from 2000. In terms of major food groups, we found that all of them except for proteins and fats correlated with increased digestive cancer rates. However, we can most likely chalk this finding up to all the food groups also correlated with total caloric intake as well. And in some cases, to the fact that each food group consisted of one or two "bad actors" which made up a large portion of its caloric content, while being associated with digestive cancer.

In terms of specific foods, there were several expected and unexpected correlations that we uncovered. Beef, milk, ice cream, and high fructose corn syrup are all well-documented culprits for digestive cancer, while foods like head lettuce, potatoes, and orange juice were unlikely correlates of cancer incidence/mortality. [High fiber foods](https://pubmed.ncbi.nlm.nih.gov/1851150/#:~:text=Abstract,%2C%20endometrial%2C%20and%20gastrointestinal%20cancer.) like avocados, hominy, peanuts, and sweet potatoes trended upwards as digestive cancer trended downwards. These types of foods are known to promote gut health and are thought to be protective against several forms of cancer. However, we also found that butter and mozzarella were negatively associated, despite our pre-existing notions of dairy products.

However, these findings are merely correlations. Other factors could contribute to why these specific foods and food groups rose/decreased over the years. Maybe people who are health conscious have a passion for peanuts. Or interest in canned peaches coincidentally waned while digestive cancer rates decreased at the level of intervention rather than prevention. Whatever the case, any allusions made here to foods that are preventive or causal of digestive cancer shouldn't be heeded; only well-designed experiments, clinical trials, or your doctor can make those kinds of claims.

In a future analysis, we could also explore other known correlates of digestive cancer such as alcohol use and smoking habits over the same time period to give more insight into what caused this decrease in digestive cancer incidence and mortality. It would be interesting to explore clusters of behavior like this which might be grouped with foods for unexpected reasons. Another analysis could look at a more granular form of the data, for instance at the state or county level. There may be unexplored factors there, like local water quality and environmental toxins, that would be interesting to unravel.
